### ISSUE TITLE
Suggestion: Mod Compatibility

### ISSUE THREAD

**Issue by Burgersim** [MysticMods/Druidcraft#17]
Hi there, I hope it's ok to post this here, but I was wondering if it would be possible for you to add some compatibility between mods to your mod.

In the Mod [Upgrade Aquatic](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic) there is a new Wood Type (Driftwood) and since your mod adds wooden beams and panels I thought it would be really nice if there could be variants of them for Driftwood too. Also not sure of all recipes of your mod yet, but maybe some of the plants and stuff from Upgrade Aquatic could even be used, opitonally, in some recipes?

The Mod [Quark ](https://quark.vazkii.net/#features )adds Bookshelves and other things made out of wood (e.g. Chests, Ladders, Vertical Planks, Vertical Slabs) for all Wood Variants, so would it be possible to add this for your added wood as well, if Quark is present?

Thanks a lot for making this mod btw, I really like it so far and really wanna use it in my next Modpack :)

**Comment by VulpTheHorseDog** [comment]
There are plans for the latter suggestion already, but I think if I were to try and create additional wood-types for beams and such from other mods, it would have to be an api I add in that allows them to do it instead. I can't be adding every other wood type let alone texture them.

**Comment by noobanidus** [comment]
For "plants and stuff from Upgrade Aquatic": honestly, I just don't think cross-mod interactions are really designed to work like this. Where an ingredient is supposed to be similar to another ingredient implemented by another mod, it should be defined as an ingredient tag.

Adding optional usage of other mods' ingredients and items fails dramatically not just when the other mod isn't installed (not to mention the hoops you have to jump through just to be able to use another mod's items in your own) but when the "optional" mod updates and changes the registration names or removes an item and all of a sudden your mod crashes whenever you load it with the latest version. 

I don't honestly see why darkwood chests (vertical planks already exist), etc, would require Quark be installed. I've heard this logic before and I really don't agree with it: these sorts of features and mods existed well before Quark did, and it could be something intrinsic to the mod rather than dependent *for no reason* on Quark.

Likewise, there are a lot of mods that add different wood types -- and more and more are being ported to 1.14.4 every day. It is *very* easy to fall into the logical fallacy of "well I'll add support for this" -- as I mentioned support is very fragile -- and I definitely agree with Vulp's suggestion of an API.

In addition, a separate mod that specifically "bridges" Druidcraft's beam system with other mods might be a better idea -- where someone who is dedicated to maintaining the bridge can put time and effort into maintaining it and making sure that it's fully functional.

I know first-hand from one of my earliest mods that you can go completely crazy with cross-compatibility (without using APIs), and it's an extremely time-consuming process. 

Finally, for the most part, while it's really nice to include cross-mod interaction within your own mod, for the most part that becomes another significant source of responsibility and time spent, which can then detract from whatever else is currently planned.

And finally, finally, I think you'll find that CraftTweaker (and whatever other additions are made to it as 1.14.4 cycles onwards) and Data Packs will answer all of your concerns about recipes -- especially if you're trying to put together a mod pack. Take it upon yourself to learn how to change recipes and integrate multiple mods together -- that's the most important part of making a pack (in my opinion), as it allows *you* to choose how you want to cross-pollinate, rather than asking the mod author to add endless configuration options.

**Comment by VulpTheHorseDog** [comment]
Something like this is now planned for the next update, so sit tight.
