### ISSUE TITLE
Crash when not using JEI

### ISSUE THREAD

**Issue by Klaaf** [MysticMods/Druidcraft#77]
### General Information

**Describe the bug:**
The game crashes when loading a new world when JEI is not installed along Druidcraft.
Installing JEI solves the problem.

**To Reproduce:**
1. Create fresh Forge instance
2. Install only Druidcraft
3. Load new world
4. Crash

**Expected behavior:**
No crash

***

### Environment Versions

**Mystic Mods Versions**
mysticallib-1.15.2-2.0.1.jar
Druidcraft-1.15-0.4.41.jar

**Other Versions:**
Forge 31.2.45
Minecraft 1.15.2

***

### Logging Information

**Crash Report (if available):**
https://gist.github.com/Honeybadjah/87276909442567c8453173f3081b814b

**Comment by noobanidus** [comment]
I'd suggest this is actually an error with mod loading. Could you attach the complete latest.log file? I think there's probably an unreported crash during mod loading, because this crash seems to be... basically saying that "advancements aren't loaded when they should be", except it's Minecraft saying that -- not any particular mod.

**Comment by Honeybadjah** [comment]
Yeah of course. Here you go: https://gist.github.com/Honeybadjah/e375f39789b8c1aae3ff15b8fbf27acf
Thanks for your work

**Comment by VulpTheHorseDog** [comment]
All fixed!
