### ISSUE TITLE
Sleeping breaks off-hand block stacks

### ISSUE THREAD

**Issue by enduum** [MysticMods/Druidcraft#89]
**Description:**
Sleeping in a bed or bedroll with any size stack of a block in the off-hand results in that off-hand block being unable to return to its stack when placed and broken again.

**Steps to reproduce:**
1. Put a stack of dirt(/any block) in the off-hand.
2. Sleep in any bed or druidcraft bedroll.
3. Place on the ground a block from the off-hand.
4. Break the block.
5. Block doesn't return to the stack in your off-hand. Shuffling things around your inventory/removing the stack from your off-hand will not fix it. The only way to combine stacks again is to place every block from your off-hand stack and break them.
6. Bug will reoccur with your "new" stack if you put it in the offhand and sleep again.

**Expected behavior:**
Blocks returning to their former stack as usual.

- Forge: 36.0.1
- Minecraft: 1.16.5
- Druidcraft: 0.4.5

**Comment by noobanidus** [comment]
That is a bit strange, looks like the NBT is being applied to both the bed item and to the off-hand. I'll look into it.

**Comment by Vaelzan** [comment]
That explains a lot. I've been trying to track down what was causing that without success until I happened to see this. It has been bugging me with torches during my playthrough!

**Comment by noobanidus** [comment]
I think the commit I've just pushed should fix this. It was making an assumption about the event only firing from sleeping bags, which I've fixed by having it bail if neither the main hand nor the off hand are a sleeping bag when you wake up.

**Comment by Vaelzan** [comment]
There's a typo in the commit, breaking the travel pack bedroll functionality if it is in the player's main hand. The code you committed immediately exits out of the method if the main hand IS holding a travel pack, but doesn't exit out if it ISN'T a travel pack. 

The code for off-hand is correct, where it returns out of the method if it isn't a travel pack, but you probably want to skip that check if the main hand is already known to be holding a travel pack so that it doesn't change the itemStack value.
