### ISSUE TITLE
Suggestion:slim beetle

### ISSUE THREAD

**Issue by Wotzinator** [MysticMods/Druidcraft#9]
a slimer beetle that hanst gotten to fat to fly so you can tame it and raide it,it should also be able to wear armor .it wont have inventory space and lower health than the normal beetle.

i know that the other beetle just released but i thought it would fit especially because the beetle seems to be intentionally fat

**Comment by VulpTheHorseDog** [comment]
While it would be pretty nice to have a flying, rideable mob in Druidcraft, it's something I lack the experience to code and I just don't think it will be a thing anytime soon. That and this is the beetle, and I don't think I want to have several different kinds, especially since the beetle is supposed to be hard to kill specifically because of its chitin on top of a few other things.

**Comment by duely** [comment]
Personally, I feel like adding a flying beetle defeats the purpose of having the beetle mount in the first place, because in the choice between a mount that fights for you & carries a lot of stuff versus one that flies, I can pretty much guarantee you that everyone would pick "one that flies".

Flying is a very serious balance issue and it should be addressed properly; flying entity mounts are notoriously hard to code and balance properly as well, and personally are the sort of thing that I would consider "end game" content.
